### ISSUE TITLE
Feature: Hotkeys

### ISSUE THREAD

**Issue by aprzn123** [aprzn123/TheThirdCan#15]
It would be useful to be able to do something like ctrl+enter to answer, or something else to skip.

**Comment by leonn00albert** [comment]
I added hot keys for the answer page

ctrl + enter -> answer
s -> save
backspace -> skip

**Comment by aprzn123** [comment]
Implemented by #21; will close if/when that is merged.

**Comment by aprzn123** [comment]
Thank you!
