### ISSUE TITLE
Suggestion: Import/Export settings

### ISSUE THREAD

**Issue by JackDyre** [aprzn123/TheThirdCan#30]
With many updates coming soon, it would be nice to be able to export my settings (maybe a sting or a text file or something) that I can import into the updated extension so I dont have to change all my setting back from the defaults. Its not that much of an issue to change my settings back now, but I would assume as this project grows, there will be many more settings involved.

Alternatively, is there a way to store the settings locally in cache or something? 

Either way import/exporting setting could also be used for installing the extension on a new device etc

**Comment by JackDyre** [comment]
Yeah im using google chrome

**Comment by aprzn123** [comment]
Settings import/export is actually super easy, although we should probably incorporate it into #22.

**Comment by JackDyre** [comment]
Should I close this now that it is incorporated in #22 ?

**Comment by aprzn123** [comment]
I wasn't sure if we should leave it up as a reminder, but it probably makes more sense to mention it there directly.
