### ISSUE TITLE
dev dependencies

### ISSUE THREAD

**Issue by HumanoidSandvichDispenser** [aprzn123/TheThirdCan#40]
I wonder if it is fine to include dev dependencies, since it was stated that [there should be no node_modules](https://github.com/aprzn123/TheThirdCan/issues/22#issuecomment-1457508186). I assume that was to make packaging easier, and dev dependencies are only used for testing/development. The reason I ask is for code linters and prettifiers, so I am wondering if it is okay.

I think the code formatting should be another issue, but that should probably be discussed when #22 is resolved.

**Comment by aprzn123** [comment]
I think linting and prettifying would be useful to use tools for. Once we set a standard, we can try to set up Github CI for that, too. Dev dependencies are fine, node is just painful and I would rather not require people use it.
